#!/usr/bin/env bash
set -euo pipefail

if [[ "$(uname)" != "Darwin" ]]; then
  echo "notesCapture setup is currently supported on macOS."
  echo "The storage format is OS-agnostic and Dropbox-friendly for future Windows/Android clients."
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="$REPO_ROOT/bin"
BINARY="$BIN_DIR/notesCapture"
HAMMERSPOON_USER_DIR="$HOME/.hammerspoon"
HAMMERSPOON_USER_INIT="$HAMMERSPOON_USER_DIR/init.lua"
LAUNCH_AGENT_DIR="$HOME/Library/LaunchAgents"
HAMMERSPOON_PLIST="$LAUNCH_AGENT_DIR/com.notescapture.hammerspoon.plist"
SYNC_PLIST="$LAUNCH_AGENT_DIR/com.notescapture.sync.plist"
APP_SUPPORT_DIR="$HOME/Library/Application Support/notesCapture"
SYNC_PROCESS_SCRIPT="$APP_SUPPORT_DIR/process_inbox.sh"
SYNC_MATERIALIZE_SCRIPT="$APP_SUPPORT_DIR/materialize_notes.sh"
SYNC_LOG_OUT="$APP_SUPPORT_DIR/sync.stdout.log"
SYNC_LOG_ERR="$APP_SUPPORT_DIR/sync.stderr.log"
REPO_HAMMERSPOON_INIT="$REPO_ROOT/hammerspoon/init.lua"
CONFIG_DIR="$REPO_ROOT/config"
CONFIG_ENV="$CONFIG_DIR/config.env"
GENERATED_LUA="$CONFIG_DIR/generated.lua"
IOS_SETUP_FILE="$REPO_ROOT/mobile/ios/SHORTCUT_SETUP.txt"
DATA_DIR="${NOTESCAPTURE_DATA_DIR:-}"
PREFERRED_MODE=""
DROPBOX_ROOT=""

usage() {
  cat <<EOF
Usage: ./setup.sh [options]

Options:
  --data-dir PATH      Use a specific data directory
  --use-dropbox        Prefer Dropbox for shared data
  --use-repo-data      Store data inside the repo at ./data
  --help               Show this message
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --data-dir)
      DATA_DIR="$2"
      shift 2
      ;;
    --use-dropbox)
      PREFERRED_MODE="dropbox"
      shift
      ;;
    --use-repo-data)
      PREFERRED_MODE="repo"
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

ensure_command() {
  local cmd="$1"
  local message="$2"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "$message"
    exit 1
  fi
}

resolve_path() {
  python3 - "$1" <<'PY'
from pathlib import Path
import sys
print(Path(sys.argv[1]).expanduser().resolve())
PY
}

find_dropbox_root() {
  local candidate

  if [[ -d "$HOME/Library/CloudStorage" ]]; then
    candidate="$(find "$HOME/Library/CloudStorage" -maxdepth 1 -type d -name 'Dropbox*' 2>/dev/null | head -n 1 || true)"
    if [[ -n "$candidate" ]]; then
      resolve_path "$candidate"
      return
    fi
  fi

  if [[ -d "$HOME/Dropbox" ]]; then
    resolve_path "$HOME/Dropbox"
    return
  fi
}

choose_data_dir() {
  if [[ -n "$DATA_DIR" ]]; then
    return
  fi

  local dropbox_root
  dropbox_root="$(find_dropbox_root || true)"
  DROPBOX_ROOT="$dropbox_root"

  if [[ "$PREFERRED_MODE" == "repo" ]]; then
    DATA_DIR="$REPO_ROOT/data"
    return
  fi

  if [[ -n "$dropbox_root" ]]; then
    DATA_DIR="$dropbox_root/notesCapture-data"
    return
  fi

  DATA_DIR="$REPO_ROOT/data"
}

install_hammerspoon() {
  if [[ -d "/Applications/Hammerspoon.app" ]]; then
    return
  fi

  if command -v brew >/dev/null 2>&1; then
    echo "Installing Hammerspoon..."
    brew install --cask hammerspoon
    return
  fi

  echo "Homebrew is required to auto-install Hammerspoon."
  echo "Install Homebrew, then rerun ./setup.sh"
  exit 1
}

build_helper() {
  ensure_command swiftc "swiftc was not found. Install Xcode Command Line Tools, then rerun ./setup.sh"
  mkdir -p "$BIN_DIR"
  echo "Building notesCapture helper..."
  swiftc "$REPO_ROOT/quicknote.swift" -o "$BINARY"
}

ensure_storage_dirs() {
  mkdir -p \
    "$DATA_DIR" \
    "$DATA_DIR/entries" \
    "$DATA_DIR/ingress/dropbox" \
    "$DATA_DIR/ingress/local"
}

write_config_files() {
  mkdir -p "$CONFIG_DIR"

  cat > "$CONFIG_ENV" <<EOF
REPO_ROOT="$REPO_ROOT"
DATA_DIR="$DATA_DIR"
BINARY="$BINARY"
EOF

  cat > "$GENERATED_LUA" <<EOF
return {
  dataDir = [[${DATA_DIR}]]
}
EOF
}

write_hammerspoon_loader() {
  mkdir -p "$HAMMERSPOON_USER_DIR"
  cat > "$HAMMERSPOON_USER_INIT" <<EOF
-- Auto-generated by notesCapture setup
-- Edit this file if you want to load additional Hammerspoon config.
dofile([[${REPO_HAMMERSPOON_INIT}]])
EOF
}

write_hammerspoon_launch_agent() {
  mkdir -p "$LAUNCH_AGENT_DIR"
  cat > "$HAMMERSPOON_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.notescapture.hammerspoon</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/open</string>
    <string>-a</string>
    <string>Hammerspoon</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <false/>
</dict>
</plist>
EOF

  launchctl unload "$HAMMERSPOON_PLIST" >/dev/null 2>&1 || true
  launchctl load "$HAMMERSPOON_PLIST"
}

write_sync_support_scripts() {
  mkdir -p "$APP_SUPPORT_DIR"

  cat > "$SYNC_MATERIALIZE_SCRIPT" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

DATA_DIR="${1:-}"
if [[ -z "$DATA_DIR" ]]; then
  echo "Usage: $0 <data-dir>"
  exit 1
fi

ENTRIES_DIR="$DATA_DIR/entries"
NOTES_FILE="$DATA_DIR/notes.txt"
TMP_FILE="$DATA_DIR/.notes.txt.tmp"
ENTRY_LIST="$DATA_DIR/.notesCapture-entry-list.tmp"

mkdir -p "$DATA_DIR"
find "$ENTRIES_DIR" -type f -name '*.txt' 2>/dev/null | sort > "$ENTRY_LIST" || true

if [[ ! -s "$ENTRY_LIST" ]]; then
  rm -f "$ENTRY_LIST"
  : > "$NOTES_FILE"
  exit 0
fi

: > "$TMP_FILE"
while IFS= read -r file; do
  [[ -n "$file" ]] || continue
  if ! grep -q '[^[:space:]]' "$file"; then
    continue
  fi

  base="$(basename "$file")"
  prefix="${base%%--*}"
  if [[ "$prefix" == "$base" ]]; then
    prefix="${base%.txt}"
  fi

  text="$(python3 - "$file" <<'PY'
from pathlib import Path
import sys
print(Path(sys.argv[1]).read_text(encoding='utf-8').strip())
PY
)"
  if [[ -z "$text" ]]; then
    continue
  fi

  display_ts="$(echo "$prefix" | sed -E 's/^([0-9]{4}-[0-9]{2}-[0-9]{2})_([0-9]{2})-([0-9]{2})-([0-9]{2})$/\1 \2:\3:\4/')"
  printf '[%s]\n%s\n\n' "$display_ts" "$text" >> "$TMP_FILE"
done < "$ENTRY_LIST"

mv "$TMP_FILE" "$NOTES_FILE"
rm -f "$ENTRY_LIST"
EOF

  cat > "$SYNC_PROCESS_SCRIPT" <<EOF
#!/usr/bin/env bash
set -euo pipefail

DATA_DIR="\${1:-}"
if [[ -z "\$DATA_DIR" ]]; then
  echo "Usage: \$0 <data-dir>"
  exit 1
fi

ENTRIES_DIR="\$DATA_DIR/entries"
INGRESS_DIR="\$DATA_DIR/ingress"
DROPBOX_INGRESS_DIR="\$INGRESS_DIR/dropbox"
LOCAL_INGRESS_DIR="\$INGRESS_DIR/local"
MATERIALIZE_SCRIPT="${SYNC_MATERIALIZE_SCRIPT}"
TMP_LIST="\$DATA_DIR/.notesCapture-inbox-list.tmp"

mkdir -p "\$ENTRIES_DIR" "\$DROPBOX_INGRESS_DIR" "\$LOCAL_INGRESS_DIR"

imported_any=0

import_from_source_dir() {
  local source_dir="\$1"
  local source_name="\$2"
  local device="\$3"
  local archive_dir="\$source_dir/archive"

  mkdir -p "\$source_dir" "\$archive_dir"
  find "\$source_dir" -maxdepth 1 -type f \( -name '*.txt' -o -name '*.md' \) | sort > "\$TMP_LIST" || true

  while IFS= read -r file; do
    [[ -n "\$file" ]] || continue

    if ! grep -q '[^[:space:]]' "\$file"; then
      mv "\$file" "\$archive_dir/\$(basename "\$file").empty"
      continue
    fi

    local mtime timestamp year month day unique_id entry_dir entry_file
    mtime="\$(stat -f '%m' "\$file")"
    timestamp="\$(date -r "\$mtime" '+%Y-%m-%d_%H-%M-%S')"
    year="\$(date -r "\$mtime" '+%Y')"
    month="\$(date -r "\$mtime" '+%m')"
    day="\$(date -r "\$mtime" '+%d')"
    unique_id="\$(uuidgen | tr '[:upper:]' '[:lower:]' | cut -c1-8)"

    entry_dir="\$ENTRIES_DIR/\$year/\$month/\$day"
    mkdir -p "\$entry_dir"
    entry_file="\$entry_dir/\$timestamp--\$source_name--\$device--\$unique_id.txt"

    cp "\$file" "\$entry_file"
    mv "\$file" "\$archive_dir/\$(basename "\$file").imported"
    imported_any=1
  done < "\$TMP_LIST"
}

import_from_source_dir "\$DROPBOX_INGRESS_DIR" "mobile-capture" "dropbox-ingress"
import_from_source_dir "\$LOCAL_INGRESS_DIR" "mac-hotkey" "local-ingress"

rm -f "\$TMP_LIST"

if [[ "\$imported_any" -eq 1 || ! -f "\$DATA_DIR/notes.txt" ]]; then
  "\$MATERIALIZE_SCRIPT" "\$DATA_DIR"
fi
EOF

  chmod +x "$SYNC_MATERIALIZE_SCRIPT" "$SYNC_PROCESS_SCRIPT"
}

disable_sync_launch_agent() {
  launchctl unload "$SYNC_PLIST" >/dev/null 2>&1 || true
  rm -f "$SYNC_PLIST"
}

write_ios_setup_file() {
  mkdir -p "$(dirname "$IOS_SETUP_FILE")"

  if [[ -z "$DROPBOX_ROOT" ]]; then
    DROPBOX_ROOT="$(find_dropbox_root || true)"
  fi

  local resolved_data_dir
  resolved_data_dir="$(resolve_path "$DATA_DIR")"

  if [[ -n "$DROPBOX_ROOT" && "$resolved_data_dir" == "$DROPBOX_ROOT"* ]]; then
    local dropbox_relative
    dropbox_relative="${resolved_data_dir#"$DROPBOX_ROOT"}"
    dropbox_relative="${dropbox_relative#/}"

    cat > "$IOS_SETUP_FILE" <<EOF
notesCapture iPhone / iPad Dropbox setup

1. Install the Dropbox app and Apple Shortcuts.
2. Create a Shortcut named notesCapture.
3. Add these actions:
   - Ask for Input (Text, prompt: Quick note)
   - Current Date
   - Format Date -> Custom -> yyyy-MM-dd_HH-mm-ss
   - Text -> use the note text from Ask for Input
   - Save File to Dropbox
4. Save the file into this Dropbox folder:
   /${dropbox_relative}/ingress/dropbox
5. Recommended file name:
   [Formatted Date]-iphone.txt
6. On your Mac, notesCapture will automatically import those ingress files into:
   ${resolved_data_dir}/entries
7. Your merged timeline stays here:
   ${resolved_data_dir}/notes.txt

Save new mobile captures only to ingress/dropbox/.
EOF
    return
  fi

  cat > "$IOS_SETUP_FILE" <<EOF
notesCapture mobile setup

Your current data directory is not inside Dropbox:
${resolved_data_dir}

That means Mac capture works, but phone capture will not sync yet.

To enable iPhone capture, rerun setup with a Dropbox-backed data directory, for example:
./setup.sh --data-dir "$HOME/Dropbox/notesCapture-data"

Once your data directory lives in Dropbox, notesCapture will use this mobile contract:
- phone writes plain text files into ingress/dropbox/
- Mac imports them into entries/
- notes.txt is regenerated automatically
EOF
}

restart_hammerspoon() {
  killall Hammerspoon >/dev/null 2>&1 || true
  sleep 1
  open -a Hammerspoon
}

main() {
  choose_data_dir
  install_hammerspoon
  ensure_command bash "bash is required"
  build_helper
  ensure_storage_dirs
  write_config_files
  write_hammerspoon_loader
  write_hammerspoon_launch_agent
  write_sync_support_scripts
  disable_sync_launch_agent
  chmod +x "$REPO_ROOT/scripts/materialize_notes.sh" "$REPO_ROOT/scripts/process_inbox.sh" "$BINARY"
  "$SYNC_PROCESS_SCRIPT" "$DATA_DIR"
  write_ios_setup_file
  restart_hammerspoon

  echo
  echo "notesCapture is set up."
  echo "Project: $REPO_ROOT"
  echo "Data directory: $DATA_DIR"
  echo "Hotkey: Option + Space"
  echo "Merged notes: $DATA_DIR/notes.txt"
  echo "Mobile Dropbox ingress: $DATA_DIR/ingress/dropbox"
  echo "iPhone shortcut guide: $IOS_SETUP_FILE"
  echo
  echo "If macOS prompts for permissions, allow Hammerspoon in:"
  echo "- Privacy & Security > Accessibility"
  echo "- Privacy & Security > Input Monitoring"
}

main "$@"
