#!/usr/bin/env bash
set -euo pipefail

if [[ "$(uname)" != "Darwin" ]]; then
  echo "notesCapture setup is supported on macOS only."
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="$REPO_ROOT/bin"
BINARY="$BIN_DIR/hotkey-notes"
NOTES_FILE="$REPO_ROOT/notes.txt"
HAMMERSPOON_USER_DIR="$HOME/.hammerspoon"
HAMMERSPOON_USER_INIT="$HAMMERSPOON_USER_DIR/init.lua"
LAUNCH_AGENT_DIR="$HOME/Library/LaunchAgents"
LAUNCH_AGENT_PLIST="$LAUNCH_AGENT_DIR/com.notescapture.hammerspoon.plist"
REPO_HAMMERSPOON_INIT="$REPO_ROOT/hammerspoon/init.lua"

ensure_command() {
  local cmd="$1"
  local message="$2"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "$message"
    exit 1
  fi
}

install_hammerspoon() {
  if [[ -d "/Applications/Hammerspoon.app" ]]; then
    return
  fi

  if command -v brew >/dev/null 2>&1; then
    echo "Installing Hammerspoon..."
    brew install --cask hammerspoon
    return
  fi

  echo "Homebrew is required to auto-install Hammerspoon."
  echo "Install Homebrew, then rerun ./setup.sh"
  exit 1
}

build_helper() {
  ensure_command swiftc "swiftc was not found. Install Xcode Command Line Tools, then rerun ./setup.sh"
  mkdir -p "$BIN_DIR"
  echo "Building helper..."
  swiftc "$REPO_ROOT/quicknote.swift" -o "$BINARY"
}

write_hammerspoon_loader() {
  mkdir -p "$HAMMERSPOON_USER_DIR"
  cat > "$HAMMERSPOON_USER_INIT" <<EOF
-- Auto-generated by notesCapture setup
-- Edit this file if you want to load additional Hammerspoon config.
dofile([[${REPO_HAMMERSPOON_INIT}]])
EOF
}

write_launch_agent() {
  mkdir -p "$LAUNCH_AGENT_DIR"
  cat > "$LAUNCH_AGENT_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.notescapture.hammerspoon</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/open</string>
    <string>-a</string>
    <string>Hammerspoon</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <false/>
</dict>
</plist>
EOF

  launchctl unload "$LAUNCH_AGENT_PLIST" >/dev/null 2>&1 || true
  launchctl load "$LAUNCH_AGENT_PLIST"
}

restart_hammerspoon() {
  killall Hammerspoon >/dev/null 2>&1 || true
  sleep 1
  open -a Hammerspoon
}

main() {
  install_hammerspoon
  build_helper
  touch "$NOTES_FILE"
  write_hammerspoon_loader
  write_launch_agent
  restart_hammerspoon

  echo
  echo "notesCapture is set up."
  echo "Hotkey: Option + Space"
  echo "Notes file: $NOTES_FILE"
  echo
  echo "If macOS prompts for permissions, allow Hammerspoon in:"
  echo "- Privacy & Security > Accessibility"
  echo "- Privacy & Security > Input Monitoring"
}

main "$@"
